### ISSUE TITLE
"Edit this entry" does not longer work. Perhaps related to the new edit_access functionality?

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#1]
This morning I added a new thread. Query string for the entry: m=threads&entry=180. I forgot to add the category and wanted to correct it. Clicking on "Edit this entry" shows an empty frame. Tested it for existing new, tools and threads. Same behavior. I noticed the NEW "edit_acess" functionality. Could this have something todo with it?

Note: I tried also with Chrome. I did login as adminstrator for that. Same result -> empty frame.

**Comment by gbiobob** [comment]
Yes there is work in progress on access : final big step before the release.
The issue on editing an entry is fixed

**Comment by wolverine2710** [comment]
Tested it. Works like a charm.
