### ISSUE TITLE
RSS feed Community - updates not shown in  GLOBAL RSS feeds.

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#10]
In RSS feed "EDCodex - Global - Full EDTL feed" and "EDCodex - Global - Community entries" I don´t see updates for community entries. They are however shown in "EDCodex - Updates only - Full EDTL feed" and "EDCodex - Updates only - Community entries". Example of an entry i entered and updated this morning "Elite Galaxy"

**Comment by gbiobob** [comment]
Thinks it's not an issue, I see your last addition in my RSS reader,
think it's more a cache issue of the RSS reader.
Test the small hack to refresh your RSS reader (add a parameter at the end of the url).

**Comment by wolverine2710** [comment]
Strange because I installed Bamboo fresh this morning. Hence virgin. 

I applied the "add a parameter" trick you describe in iissue #11 (https://github.com/gbiobob/EDCodex/issues/11) to force Bamboo into thinking its a new RSS feed. AFTER that the updates are shown.

So it seems it was an issue on my side, my bad.
 You can close this ticket/issue.
