### ISSUE TITLE
RSS feeds. Urls refer to the TEST site (ed-board.net) instead of the new EDCodex domain

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#11]
I´ve tested this with new entries (which results in an 404 because they are not there on ed-board.net) and with older entries. The older enries DO show the entry on ed-board.net. The urls in the RSS feed should refer (point to) to an url on the new Edcodex domain.

**Comment by gbiobob** [comment]
I miss some replacement after host migrate :/
Now it's fixed,
to force your RSS reader to update you just have to add a parameter at the end of the url like "?v=2",
exemple: http://edcodex.info/datas/rss/all-date_add.xml?v=2
RSS reader will take that as a new feed.

**Comment by wolverine2710** [comment]
Works like a charm now. I´m using the Firefox bamboo addon. It picked up the new edcodex domain by default without manual intervention. The short description however was the old one (changed a few this morning).

After using your "add a parameter" trick to create a new "EDCodex - Global - Full EDTL feed" the short description WAS correctly changed. All is fine now ;-)
