### ISSUE TITLE
Video section edit page - author name and url can´t be filled in

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#12]
You didn´t officially mention the video section as being done, so WIP and perhaps unfair to mention it. Still wanted to mention it.

The author name and url fields are not active. As in I can´t fill them in.

**Comment by gbiobob** [comment]
I've see that yesterday but on threads,
Issue is now fixed.

**Comment by wolverine2710** [comment]
Works like a charm now. Thanks.
