### ISSUE TITLE
Admin history page: Two obsolete sort/order icons

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#13]
The most left column (left of Date) doesn´t have text inside but it has an order/sort functionality icon - which does not seem to do anything. It seems this one can be removed.

The most right column has as contents always the string "view entry". The order/sort functionality seems obsolete, not needed.

Just some nittpicking ;-)

**Comment by wolverine2710** [comment]
Have you had time to look into this issue.

**Comment by gbiobob** [comment]
Not yet, will improve that in September.
