### ISSUE TITLE
Unable to remove an author after it has  been set

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#14]
Wanted to remove an author. It was a wiki article, author unknown and had set it to wikipedia in the past. Doesn´t seem to fit for me. Only author name was set. I deleted the author name, saved and it was still there. Edited article again and removed again, saved and author name is still article.

Entry name: Machine learning

**Comment by gbiobob** [comment]
There is work in progress on that, I rework completely atm the author field.
Will be fixed in the next update.

**Comment by wolverine2710** [comment]
I know but just wanted to point it out.
Will torture test the new multiple authors functionality when its out ;-)
You can close this ticket.

**Comment by gbiobob** [comment]
Multiple authors are alive on test platform (remove an author now work well)
need some visual fix + deeper test,
once done will deploy on edcodex.
