### ISSUE TITLE
After changing entries from section Thread to Community they show up twice in the search result list

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#15]
Changed section for three entries from Thread to community. Selected them by searching for the word wiki. Didn´t notice I had duplicates. After changing and searching for the word "wiki" again I found duplicates (in there twice)  in the presented search results list. Two out of three of the changed entries show up as duplicates.

Dups:
Elite: Dangerous Wiki
Lave wiki

Curiously enoug the following entry does NOT show up twice: Roguey (Space SIM Wiki)

**Comment by gbiobob** [comment]
Not really an issue and not related to changing section,
autocomplete list got both entry name and author name
but for the entry "Lave wiki", the author name is also "Lave wiki"
so it appear twice in the autocomplete list (entry name + author name).
Make a fix to avoid duplicate items for this special case.

The autocomplete list is now clean from duplicate.
Let you check.

**Comment by wolverine2710** [comment]
You are 100% correct about not being an issue, didn't tested it thorough enough. 
Indeed the dups are gone. Like the solution.
You can close the ticket.
