### ISSUE TITLE
"new " icon prefix disappears when I sort the entries.

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#16]
A few days ago I entered 4 new entries in the community section. When an entry is new it gets a "new" icon prefixing the title for a few days. There seems to be an issue with it. I can 100% reproduce this. When I go to the community section by default its sorted by "Last updated". When I enter I see 4 entries with a new icon prefix. When I sort on one of the other possibilities  (New submissions, Most updated, Alphabetical) the new icon disappears. It happens for all three - test it. When I sort again on the default "Last updated" the new icon does NOT reappear. I can force it to reappear by selecting another section say Tools and then going back to the community section. Its again  sorted by the default "Last updated". When I sort differently the new icon disappears again. 

I've taken three screenshots. Hopefully the appear here.
1) community_with_new_icon_lastupdated_default. Entering community for the first time.
2) community_no_new_icon_new_submissions. Sorting by new submissions.
3) community_with_new_lastupdated_default_reentered. Selected another section, going back to the community section.

The screenshots shown should be in the order I mentioned above.

I've not tested it for the other section - currently don't have new entries to enter and don't want to clutter the database.

UPDATE: Turned out there are two new entries in the video section also. I'm getting the exact same behavior here. The new entries are: "Elite: Dangerous - How to get the Best Graphics with Mods and Tweaks" and  "Elite: Dangerous. How to"

![community_with_new_icon_lastupdated_default](https://cloud.githubusercontent.com/assets/4365515/9073170/de988316-3aff-11e5-8714-345a3d14658d.jpg)

![community_no_new_icon_new_submissions](https://cloud.githubusercontent.com/assets/4365515/9073169/de77312a-3aff-11e5-9b91-2cd46681880e.jpg)

![community_with_new_lastupdated_default_reentered](https://cloud.githubusercontent.com/assets/4365515/9073171/de9d6c78-3aff-11e5-92c6-2f2eeb3ef960.jpg)

**Comment by gbiobob** [comment]
The "new" text was not add when it was an ajax loading when filtering the list with a filter (forgot it).
Now it's fixed, fast to test & very small issue: I close.

**Comment by wolverine2710** [comment]
I've reopened the issue, for the reason see below.

I've tested it and it works as expected. 
I do have a question though.- reason for reopening.  I've forgotten how many days after the creation of an entry the new tag should be shown. Atm only Galnet.fr does have the new tag. Entries "Elite Galaxy" and "Universal cartograpics.beta" are however from the same day (august the 1st). A time is not shown in EDCodex and only by looking at the database I can figure that out. It is possible that Galnet.fr is slightly newer then the other two. Could you please dig in and tell me why only Galnet.fr atm has the new tag?

**Comment by gbiobob** [comment]
The "new" tag is show during the first 7 day (relative to date-time submission) <=> the first 168 hrs.
Your entries have been submitted the 31-07 before 08:20 UTC (in your timetone 07:20) so the "New" tag have been removed this morning for this two entries (yesterday, when made my test the tag was here ;))
Galnet have been submitted the 01-08 at 00:56 UTC : not the same day, so will disappear tonight at 0:56 (11:56 for us).

Time is relative so made some design choices to have something suitable for common users,
here an extract of a mail send last month:

> everything use UTC time,
> so in admin, every datetime are UTC values
> and for public side in entries list & history list in an entry detail, 
> I've replace visible datetime with something more suitable for everyone in the world,
> before we got for an entry updated in the last 24 hours :
> Updated "Today at 08:30"
> now we have :
> Updated "6 hours ago"
> (After 48 show a date without time)
> With this kind of datetime format no need to take care on user localization.

An evolve for registered user could be to let us choosing their timezone to show them a full datetime depending on their localization.

**Comment by wolverine2710** [comment]
Lets discuss this further after you have returned next week.

**Comment by wolverine2710** [comment]
**If I understand it all correctly then YES I very much like your suggestion:** "An evolve for registered user could be to let us choosing their timezone to show them a full datetime depending on their localization".

For me its important to being able to see exactly when something has been added/updated. Makes admin tasks easier. So a setting in "personal space" would be nice.
