### ISSUE TITLE
Sort order NOT remembered when reentering a section - always sorted by the default "Last updated"

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#17]
Perhaps this is by design or not yet implemented.  

When selecting a section (Tools,Threads,Community and Videos) by default the full list is shown AND its the full list is sorted by "Last updated". I select the tools section, sort on another option ((New submissions, Most updated, Alphabetical), ie Alphabetical and then select another section, say Threads. When I select Tools again it hasn't remembered my previous sorting order and its again sorted by the default "Last updated"

IIrc I've seen the same behavior for the tabs/menus in the admin section.

**Comment by gbiobob** [comment]
Not implemented, when moving on an other menu or completly reload the active page: all filters (and so order) are reset.
Keep this issue open as en enhancement, could be useful to save a chosen order.

**Comment by wolverine2710** [comment]
Indeed very useful. Perhaps something for the "personal space" options of registered users as an extra perk. Other implementations are possible. I Will create an entry  for it in in the Q&A tool. This might encourage commanders to start using that;-) As in when they might feel more comfortable with it when a few entries are already there.

**Comment by gbiobob** [comment]
Now the sort is save during the navigation for everyone (registered or not)
Later I will add the possibility save a default sort for registered users.

**Comment by wolverine2710** [comment]
Tested it. Works like a charm.

When you have added it to the roadmap I think you can close this ticket.
