### ISSUE TITLE
Changed author name. A search displays the original author name - change not picked up after 50 minutes

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#18]
With the new multiple authors functionality its now also possible to change (and remove) an existing author name. For Tool entry "Commodity Price Grabber" the author has two names. One on FD and one on the Reddit forum. I did set the author name to "CashMoney aka DestroyBoy on reddit" in the past. I now have split it up now.  
Author name 1: DestroyBoy (reddit)
Author name 2: CashMoney

With search I can search for Title and Author name. That info is stored as a JSON file in the local storage iirc.  When I search for the old author "cash" or "Destroy" in the drop down list I see as search result "CashMoney aka DestroyBoy on reddit" (ie old name). When I select it in the result list in the middle frame the results are shown for "CashMoney aka DestroyBoy on reddit". Here there a no matches.

According to the history the change has been made 50 minutes ago. Tested it also on my main computer with Firefox. It shows the same behavior. Firefox used on both computers is 39.0

Started Chrome on my second computer. This computer and the chrome probably has not seen EDCodex before. Searching for cash shows on result -> CashMoney. Searching for "Destroy" shows as result "DestroyBoy". Hence it works correctly there.Started Chrome also on my main computer. Did the search. Getting the same correct search results.

**Comment by wolverine2710** [comment]
When checking the issue the next day it has been resolved. As in the browser has picket up the changes. Will keep an eye on this behavior to see if it happens again. In the past it had something to do with the local storage not recognizing there was something changed at the EDCodex website.

**Comment by gbiobob** [comment]
Now the static search file is updated every minutes.
If it was a time issue, it should be ok now.

**Comment by wolverine2710** [comment]
Did some testing. Did untrash  entry "TEST REG 2". I changed author biobobtest into wolverinetest. Waited so that script ran at the one minute interval.

**It looks as if the mentioned issue has disappeared. Its replaced by another issue.**

**Noticed behavior:**
1. Searched for biobobtest. It does not show up any longer in the autocomplete of search. I could have sworn that at first it did turn up but later not any longer. Perhaps I tested before the script ran....
2. Searched for wolverinetest. Autocomplete does not show it. As in no match found.
3. See bullet (2). BUT when hitting enter the main page shows as result entry "TEST REG 2"
4. Variation on (2). Searching for test, autocomplete shows [thread] "All Weapon Stats in Actual Values Test Results (Stage 1 – Shield DPS)". It has the word test in it. BUT when I hit enter aside from the mentioned thread I also get the untrashed "TEST REG 2" entry. 

I hope it makes sense. You can test it yourself by using for example  "TEST REG 2". 
Note: I've trashed/archived it after the test.
