### ISSUE TITLE
Sometimes in the edit page I see an extra/empty author line.

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#19]
Might be related to issue 14 ( https://github.com/gbiobob/EDCodex/issues/14). Before the new multiple authors functionality it was not possible to remove an existing author. Now its possible. Wanted to delete the author wikipedia for an entry. Did go to the edit page and noticed something. It shows an author line which is filled in AND it shown an empty/extra author line above it.  It might be related to the fact that for issue 14 I tried to remove that  auhor (wikipedia)  but wasn't able to. 
I'm getting an extra/empty author name line (which I assume can just simply remove)  for entry: "Machine learning". I've tested this on my main PC and on my secondary PC.

The issue I've noticed seems not to exist  for other Tools and Threads edit pages I've tested it with. As in I don't see an empty/extra author line. 

Not that important but still wondering how this could/can occur.

**Comment by gbiobob** [comment]
Yes think it was due to the issue 14: have add some empty data, 
I've clean up the database,
Should be ok now (in the new submission system for authors field, empty authors are deleted).

**Comment by wolverine2710** [comment]
The extra line is indeed removed. 

I've noticed a small inconsistency:
1. When using "Add an entry" for Tools,Threads, Community and Video. The authors section has an empty author name + url line. Good as it encourages commanders to fill it in.
1. When going to edit for an **existing** entry NO empty author name + url is shown. It just shows "+ Add an author"

I think its a very minor issue. Just wanted to point it out.
In principle the ticket can be closed.

**Comment by wolverine2710** [comment]
Example of entry which has the behavior described above: "Infographic about the profits of exploring".
I will NOT fill that entry with author name + url so you can check it out. Please let me know when I can fill it in. Atm haven't been able to find the author or thread anyway....

**Comment by wolverine2710** [comment]
I've filled in the author for "Infographic about the profits of exploring" (EDC_unknown) so the evidence is gone. Have checked again today and the behavior is still there. Its ofc still a very minor issue but its a small inconsistency in EDCodex. 

The behavior can easily be verified/reproduced by going to admin->no atuhors. Select one for the neither the name and url has been set and go to edit for that entry. What is described in post three of this issue can be watched then. Copy/paste: When going to edit for an existing entry NO empty author name + url is shown. It just shows "+ Add an author".
