### ISSUE TITLE
Search can not find entries I entered yesterday.

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#2]
Yesterday I entered the following entries. See admin-history for the urls.

Placeholder. List of Earth-like planets, v2 -- with google spreadsheet
Placeholder. 100 Stop Imperial Trade Circuit. Average 1164cr/ton/stop. Tour the Empire!
Placeholder -- EDAssets - A website containing E:D images and vectors for content creators 

**Firefox** and **Chrome**
Using the search field and searching for "placeholder" reveals NO search results in a list. BUT when I press enter in the search field the placeholder entries are shown in a frame.

**Comment by wolverine2710** [comment]
Did some more digging. There is a difference between FF and chrome. When search for "placeholder" Chrome shows "Placeholder -- EDAssets - A website containing E:D images and vectors for content creators" in the search list. FF does NOT show this entry.

Note: The add entry date for the mentioned entry is approx the same as the two  other placeholder entries I added yesterday. Those are NOT shown in the search result list.

**Comment by gbiobob** [comment]
Miss to upload a file on last update,
now everything should be ok.

**Comment by wolverine2710** [comment]
Tested it. Works like a charm (again) on FF and Chrome. Thanks for the quick fix.
