### ISSUE TITLE
Removing a link. Popup text: "Do you really want to disable "undefined" ?" 

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#21]
Not really a bug but more of a refinement.

When deleting a link a popup appears with the text: "Do you really want to disable "undefined" ?" You might want to consider changing that into a more appropriate name.

**Comment by gbiobob** [comment]
Add missing text for the alert.

**Comment by wolverine2710** [comment]
Tested it. Works like a charm. 
You can close the ticket.

Note: Also tested the new "Add an image" functionality. Also works correctly ;-)
