### ISSUE TITLE
Edit page. Author name and author url fields don't have an explanation text any longer.

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#22]
Most likely linked to the new multi-author functionality. In the past iirc a text was shown for both fields. Similar to the "Link" field. For author name and author url they don't longer exist.

**Comment by wolverine2710** [comment]
Have you perhaps had time to look into this small issue?

**Comment by gbiobob** [comment]
Not yet, will be for September too (atm I think the field are enough explicit with the label)
