### ISSUE TITLE
Admin only. Announcements page: Disable and Trash option don't display a text - popup empty.

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#23]
When clicking on "Disable" and/or "Trash" a popup appears with an OK and cancel button. No text like "Do you want to Disable this announcement" or "Do you want to trash this announcement" is shown.

**Comment by gbiobob** [comment]
Should be fixed.

**Comment by wolverine2710** [comment]
Have tested it again. Now I'm getting a different behavior. I've tested with chrome and Firefox. Last week tested in on a laptop. Didn't test with chrom iirc but did test with FF. Getting the same behavior as soon in the screenshots. Not 100% sure but can't remember having seen the "prevent this page from opening additional dialogs" message on the FF popup last week. BUT didn't include a screenshot so have no proof :-(

Chrome
![chrome_disable_trash_announcement](https://cloud.githubusercontent.com/assets/4365515/9429506/77526474-49d2-11e5-980b-07acc7c846f0.jpg)

Firefox
![ff_disable_trash_announcement](https://cloud.githubusercontent.com/assets/4365515/9429508/832e3b88-49d2-11e5-9b20-131321da6c2a.jpg)

Clicking on OK DOES enable,trash the entry. 

Curious enough with other actions which involve a popup the text is shown. Two examples are shown below, for chrome and firefox. Its for deleting the author of a tool. Did use add entry->tool for that. There seems to be a small difference in behavior between enable,trash an announcement and deleting for example an author.

Chrome
![chrome_delete_author_for_tool_entry](https://cloud.githubusercontent.com/assets/4365515/9429533/9aa28dcc-49d3-11e5-9dbe-4529ad54d980.jpg)

Firefox 
![ff_delete_author_for_tool_entry](https://cloud.githubusercontent.com/assets/4365515/9429535/a2d39d1a-49d3-11e5-97f4-84a06d703c33.jpg)

Its entirely possible its because of default security settings in the browser but I'm getting it for two different systems.

If you need more information or additional tests, please let me know.

**Comment by gbiobob** [comment]
Not really an issues, as an admin you have multiple popup windows so the browser warn  you,
I can solve that with handmade popup (I keep this issue open to take a look at that)

**Comment by wolverine2710** [comment]
Have you had time to look at it?

I've noticed that the behavior (no text shown) depends on how many times you have used it. It seems some sort of toggle. First time behavior X, second time behavior Y, third time again behavior X. 
Note; When I refresh a page I do get a text (on some pages) iirc. Not tested it for a while and this comment is from memory. Its not that important because as you said it probably  is way less of an issue with non admins.

Still if there is a way to get exactly the same behavior (with text) for all popups, that would be great. Handmade or not.
