### ISSUE TITLE
Regular user granting another user access to his entry.  Clicking Edit by that user results in a blank screen

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#24]
In a PM I was notified by a user that he got a blank screen when trying to edit an entry. The entry was a special one. The owner of that entry gave him access to his entry with "Manage access". Note: The mentioned  "Is the creator of the entry" flag below is NOT accessible for normal users. Only admin. Hence the issue happens everytime for regular users AFAIK. A relevant snippet from  a PM I did sent back. 

I can REPRODUCE your issue. I enabled a trashed (archived) tool entry. Used "manage access" to give user wolverinesimple (regular user) access to this entry. Did NOT set flag "Is the creator of the entry" flag. Logged out as admin, logged in as wolverinesimple. When clicking "Edit" I also got a blank screen. Screenshot created. Logged out. Logged in as admin. Used "manage access" to give user wolverinesimple access to this entry. This time I DID SET the "Is the creator of the entry" flag. Logged out as admin. Logged in as wolverinesimple. This time when clicking Edit I got the edit page. Made a small change and saved. Hence it worked. Afterwards trashed the entry again.

Conclusion: Afaik its a reproducible issue and its seems related to the "Is the creator of the entry" flag.   

Screenshot:
![edit_page_blank_screen](https://cloud.githubusercontent.com/assets/4365515/9331055/6f1223e4-45bd-11e5-8a9e-2790ecefd40f.jpg)

**Comment by gbiobob** [comment]
It's should be ok now, the edit form was restricted to users with creator status only.
Wait for an other testing before closing this issue.

**Comment by wolverine2710** [comment]
Re did the tests for EDSM.  Tested with "Is the creator of the entry" set and not set. The edit page appears in both cases and I could save the entry. 

Actually the with " "Is the creator of the entry" set was not correct. I used wolverine2710 (admin) for that. Test it again with one of test entries. I could edit and save the entry with user wolverinesimple.

I think the ticket can be closed.
