### ISSUE TITLE
Admin->Pending claim ownership: Always shows (0) instead of number of pending ownwership request, like "Pending claim ownership (1)"

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#25]
Noticed it this week (again). In the admin tool the following was shown: "Pending claim ownership (0)" . Checked it out anyway and found a claim ownership request for a user. Tested it today with account wolverinesimple and used the "claim ownership" button for entry "EDCodex"".  Even after 25 minutes "Pending claim ownership (0)" was shown. But when entering the tool I found out that my ownership claim was there - with the correct timestamp. Can you please have a look at it.

**Comment by wolverine2710** [comment]
Checked later that day the admin page and NOW it shows  "Pending claim ownership (1)". Hence it looks as if there is a script which checks things and that script does not run every minute or so.

**Comment by gbiobob** [comment]
There was a problem but made a fix yesterday but no time to answer on issues.
(nb: refreshed in relatime)

This issue and https://github.com/gbiobob/EDCodex/issues/26
are fixed now.
