### ISSUE TITLE
"Admin->Moderated tools" shows incorrect number. Related to "trashed" entries.

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#26]
Atm Admin->Moderated tools (7) is shown. When entering this admin tool I however see 3 entries which have been disabled (moderated). It looks as if (7) reflects the number of entries which have been recently trashed.On 2015-08-24 I archived (trash) 6 entries. On 2015-09-30 I trashed 1 entry. Hence in total 7 which is the number shown in "Moderated tools (7)". I'm not able to see a real pattern here. Can you please have a look at?

**Comment by gbiobob** [comment]
Same issue as https://github.com/gbiobob/EDCodex/issues/25
Close this one.
