### ISSUE TITLE
Search to greedy,  for at least search criteria "EDCodex". 

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#28]
Came across something strange. Didn't notice it before. When cleaning up the "duplicates", for dupe entries I set the author field to "EDCodex_Duplicate". There is a [tool] entry called "EDCodex". Also there are two [announcement] entries with "EDCodex" in the title. 

When entering EDCodex in "search" I get the following result:

![search_edcodex](https://cloud.githubusercontent.com/assets/4365515/10217941/763dccb6-6833-11e5-8dd2-8e04315957c5.jpg)

Search result lines 1,3 and 4 show the correct entries. Line 2 "[Tool]" EDCodex (biobob,wolverine2710" is to greedy and shows instead of one tool multiple entries. Basically all entries with as author "EDCodex_Duplicate", the tool with "EDCodex" in the title AND the two announcements with "EDCodex" in the title.

Haven't seen this behavior before but this is a very specific situation. Search criteria in author name, announcement title(s) and tools. Perhaps there are more situations where search fails.
Can you please have a look at it?

**Comment by gbiobob** [comment]
Not sure to understand :/
the results match to your search

**Comment by wolverine2710** [comment]
Its NOT the results, they match ;-) Its what happens when I click on a result. The issue is with [Tool] in the example. It should show a page with ONLY that tool on it. It shows much more results. Can you click on [Tool] and see what happens on your site.

**Comment by gbiobob** [comment]
Ok, I understand now,
when clicking on l3 it launch a search with the exact entry name
and the entry name is "EDCodex" so yes in results we have everything with this keyword.

In the past have add the type and authors for each tools line but still not used when you click on a item,
maybe it's confusing to have add the type and author for this particular case.

Think we can close that and maybe talk to improve the search in a other discuss.

**Comment by wolverine2710** [comment]
Now its confusing to me but its by desing. Yes we can close. I will create an email to us both as a reminder.
