### ISSUE TITLE
Categories without an entry are shown in the drop down list for Tools and for Threads - NOT for videos 

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#3]
In the past categories where shown on a categories menu tab/bar. On it where ONLY shown those categories which did have an entry for that category.  This was by design. 

This has changed, categories are now selected from a drop down list. Under the assumption that the design has not changed there is an issue. The drop down list shows all categories, also those categories which do NOT have an entry for it. 

I noticed the category test which iirc I created in the past. Wanted to delete it using the admin-category menu. The delete option was not available because there was one entry using it: "Test TZ", query string: m=tools&entry=179. This entry was trashed. Hence selecting category test in tools resulted in 0 results. I untrashed it and now selecting category test resulted in 1 match. 

Again if the design has not changed two things should happen.
1) Only show in the category drop down those categories which DO have an entry for it.
2) If a cateogry has only one entry and that entry is trashed then that category should not been shown in the drop down list.

Note: For testing I created a new category: test-wolverine. No entry is using it. It showed up immediatly in the drop down list.

Remark: I know the video section is not converted to the new drop down list system. In videos the categories test and test-wolverine are NOT shown.

**Comment by gbiobob** [comment]
The dropdown list is now filtered.

**Comment by wolverine2710** [comment]
Tested it. Indeed fixed.
