### ISSUE TITLE
EDMC Hits Release location not listed correctly

### ISSUE THREAD

**Issue by badbud65** [gbiobob/EDCodex#31]
Re: http://edcodex.info/?m=tools&entry=428

EDMC Hits Release location not listed correctly, it should be: https://github.com/inorton/EDMCHits/releases

The one listed is old and doesn't work

**Comment by wolverine2710** [comment]
I'm not sure what you mean. When I click on  http://edmc.edhits.space:8080 I see the text: Real-time system risk-levels. Remlock (EDMC) Client: here.
'Here' points to  https://github.com/inorton/EDMCHits/releases.
Am I missing something ??

**Comment by badbud65** [comment]
Yeah close it, I was being blind and didn't see the releases page on GitHub. D'oh.
