### ISSUE TITLE
Issue creating a new user

### ISSUE THREAD

**Issue by alesky78** [gbiobob/EDCodex#32]
I register my user but i dind't received the activation mail then my user is pending and not active,
i tryed to reset my password and i have recevied a mail to reset a new password,
then i redefine a new password but my user continue to be not active then i cannot login

**Comment by gbiobob** [comment]
Sometimes the automatic email for registrations are refused depending on email providers
I've manually activated your account, you should be able to login now.

**Comment by alesky78** [comment]
ok active, thanks
