### ISSUE TITLE
Every Resource's Page is Named "Elite: Dangerous API"

### ISSUE THREAD

**Issue by dylan-k** [gbiobob/EDCodex#33]
I noticed this when I had a few tabs open from the codex site, and again when I went to share one of the links. All the tabs said "Elite: Dangerous API" because that's the html title for every one of them. And because of that when I shared a link to "Elite G19s Companion App" in Discord, that's not what the link preview got named. Instead it just said "Elite: Dangerous API".  It would do wonders imo for the findability and sharing of the codex entries to make the html title's contents match the title of the item on that page.

**Comment by gbiobob** [comment]
Thanks for the feedback!
I fixed the issue on the html TITLE, seems to be ok now
