### ISSUE TITLE
edbearing is listed as active but the website is dead

### ISSUE THREAD

**Issue by HalJordan** [gbiobob/EDCodex#39]
https://edcodex.info/?m=tools&entry=414
http://www.hotdoy.ca/edbearing/

That url is still listed on the github page: https://github.com/hotdoy/EDbearing
Last update there was 5 years ago.

**Comment by gbiobob** [comment]
Thanks, 
I've replace the website url with the github repo url,
I let the tool active, I tested to download it and use it : still working

**Comment by HalJordan** [comment]
The last update was 5 years ago, and it's been archived by the original author. It's abandonware.
