### ISSUE TITLE
(Sometimes) Endless spinner for category Trading

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#4]
Experienced this 4+ times this morning. Setting a filter for category trading (23 entries) for tools results in an endless spinner - no results ever shown. Other smaller categories seem to work. Selecting All also seems to work. When the endless spinner appears and opening another tab with EdCodex and selecting trading it sometimes works, sometimes not. Doing a refresh of the page with the endless spinner seems to work. As in results shown. Can´t seem to find a pattern when it appears.

**Comment by wolverine2710** [comment]
Did a bit more digging. Its not limited to Trading. It also sometimes hangs on other categories, like API (2 entries). Also when I successfully had the trading tools displayed (23 entries) and wanted to filter on web-application I also got the endless spinner.

**Comment by gbiobob** [comment]
I make some multiple test, everything work well,
could you check the browser console to see if you get an error (MAJ+F2 on FF, F12 on Chrome) ?

**Comment by gbiobob** [comment]
I think found the problem,
issue should be fixed now.

**Comment by wolverine2710** [comment]
Have been torture testing this for quite some time. It works flawless now, so indeed it seems to be fixed. 
Ticket can be closed.
