### ISSUE TITLE
No registration mail reception

### ISSUE THREAD

**Issue by Sanghelyos** [gbiobob/EDCodex#42]
Hello, i'm not receiving any registration validation mail. Could you please contact me to get this sorted out ?
Thanks

**Comment by gbiobob** [comment]
Hi, I receive an error from your email provider: "[laposte.net](http://smtpz4.laposte.net/) said: 550
    5.7.1 Service refuse. Veuillez essayer plus tard"
    
I've manually activated your account, you should be able to login now

**Comment by Sanghelyos** [comment]
Well, i know it's not a really good email provider, there's been many issues and still are but you know, kinda lazy to migrate 10+ years of mails and accounts registered here and there.

Anyway, thanks for your reply, have a nice day :)
