### ISSUE TITLE
Dead Projects

### ISSUE THREAD

**Issue by aussig** [gbiobob/EDCodex#48]
Just browsing through the site I've found that the following projects are either dead or have dead website links (so may have moved):

1. https://edcodex.info/?m=tools&entry=142
2. https://edcodex.info/?m=tools&entry=212
3. https://edcodex.info/?m=tools&entry=285
4. https://edcodex.info/?m=tools&entry=348
5. https://edcodex.info/?m=tools&entry=169
6. https://edcodex.info/?m=tools&entry=422
7. https://edcodex.info/?m=tools&entry=265
8. https://edcodex.info/?m=tools&entry=261

**Comment by gbiobob** [comment]
Thx for the feedback!
I updated the entries
