### ISSUE TITLE
Add entry select page shows at the bottom the edit page for tools - but its a bit different.

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#5]
You are probably workin on EDC atm. When selecting add entry a page is shown where one can select tools, thread, video (and for admin also news) beneath that the edit page is shown for  tools. BUT its different then the normal edit page for tools - in particular the multi-select fields are different.

**Comment by gbiobob** [comment]
Fixed

**Comment by wolverine2710** [comment]
Indeed fixed.
