### ISSUE TITLE
Rare trades forum link is broken

### ISSUE THREAD

**Issue by designerzim** [gbiobob/EDCodex#50]
The 71 stop rare trade page leads to the old forum links and is broken:

https://edcodex.info/?m=threads&entry=92

Leads to: https://forums.frontier.co.uk/showthread.php?t=101211

It should lead to:

https://forums.frontier.co.uk/threads/71-stop-rare-trade-route-updated.101211/

Or more simply: 

https://forums.frontier.co.uk/threads/101211/

**Comment by gbiobob** [comment]
Link updated,
Thank you
