### ISSUE TITLE
Drop down selector (tools,threads,community)- pressing character doesn´t go the corresponding category any longer.

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#6]
Probably linked to the new Ajax optimization.

Normally when I click on the selector for tools, threads (and now the brand new community category) I get a drop down list. Trading because its now alphabetically ordered is at the bottom, I hate scrolling so I normally presss t and then I jump to trading (which when I click it shows the trading category). When I do that now I don´t jump but at the bottom of Firefox a field is shown with the character t and the number of matches (52), when I continue to type and type tr it show 2 matches.

Hope the explanation makes sense. On the Laptop I currently work on Chrome is not installed so couldn´t test it.

**Comment by gbiobob** [comment]
Not sure to understand,
talking about the categories dropdown on entries list ?
I make a test with the old dropdown (without ajax), no change.

**Comment by wolverine2710** [comment]
I'm indeed talking about the categories drop down menu. 

It seems I've made a mistake. With WINDOWS applications when there is a large list like a,b,c,...z and you type t the cursor moves to the entry in the list which starts with t. 

It seemed to be an issue with the Firefox browser on the laptop I was testing it with. Now I'm at home. I can NOT reproduce it on my own two PC's with Firefox.  The behavior I got was ALSO shown with other drop down menus from other sites. Hence NOT an EDCodex issue.

You can close this ticket. .
