### ISSUE TITLE
Brand new Options drop down menu - Add to fav shown on toolbar AND in the options menu

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#7]
I totally like the brand new Options drop down menu. Not going to argue with what should be in the Options menu and what on the toolbar. Just wanted to mention that "Add to Fav" is shown on the toolbar as well as in the Options menu.

**Comment by gbiobob** [comment]
Duplicate item removed

**Comment by wolverine2710** [comment]
Indeed its removed. Thanks.
