### ISSUE TITLE
Admin-translate - text string CF-First revision exists.

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#8]
I know you have cleaned the translate page which I messed up for debugging purposes. If you look at the admin-history page you notice both the texts CF-First revision and First revision. Which most likely means two things:

1) CF- First revision is not cleaned
2) First revision is hard coded.

**Comment by gbiobob** [comment]
This text is used in the desc update field when en entry is submitted,
so no it's not a hard coded text, we made new submissions when you making your text test
so this text was stored in database.
DB is now clean.

**Comment by wolverine2710** [comment]
That of course was possibilty three, which I forgot ;-) 
Checked and the CF stuf is gone. Thanks.
