### ISSUE TITLE
Community section edit page - author name and url can´t be filled in

### ISSUE THREAD

**Issue by wolverine2710** [gbiobob/EDCodex#9]
You didn´t officially mention the community section as being done, so WIP and perhaps unfair to mention it. Still wanted to mention it.

The author name and url fields are not active. As in I can´t fill them in.

**Comment by gbiobob** [comment]
Same issues as in videos,
I've fixed it everywhere.

**Comment by wolverine2710** [comment]
Works like a charm now. Thanks.
